//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidArchLifecycleAndroidViewModel")
#ifdef RESTRICT_AndroidArchLifecycleAndroidViewModel
#define INCLUDE_ALL_AndroidArchLifecycleAndroidViewModel 0
#else
#define INCLUDE_ALL_AndroidArchLifecycleAndroidViewModel 1
#endif
#undef RESTRICT_AndroidArchLifecycleAndroidViewModel

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AndroidArchLifecycleAndroidViewModel_) && (INCLUDE_ALL_AndroidArchLifecycleAndroidViewModel || defined(INCLUDE_AndroidArchLifecycleAndroidViewModel))
#define AndroidArchLifecycleAndroidViewModel_

#define RESTRICT_AndroidArchLifecycleViewModel 1
#define INCLUDE_AndroidArchLifecycleViewModel 1
#include "AndroidArchLifecycleViewModel.h"

@class AndroidAppApplication;

@interface AndroidArchLifecycleAndroidViewModel : AndroidArchLifecycleViewModel

#pragma mark Public

- (instancetype)initWithAndroidAppApplication:(AndroidAppApplication * __nonnull)application;

- (AndroidAppApplication * __nonnull)getApplication;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidArchLifecycleAndroidViewModel)

FOUNDATION_EXPORT void AndroidArchLifecycleAndroidViewModel_initWithAndroidAppApplication_(AndroidArchLifecycleAndroidViewModel *self, AndroidAppApplication *application);

FOUNDATION_EXPORT AndroidArchLifecycleAndroidViewModel *new_AndroidArchLifecycleAndroidViewModel_initWithAndroidAppApplication_(AndroidAppApplication *application) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AndroidArchLifecycleAndroidViewModel *create_AndroidArchLifecycleAndroidViewModel_initWithAndroidAppApplication_(AndroidAppApplication *application);

J2OBJC_TYPE_LITERAL_HEADER(AndroidArchLifecycleAndroidViewModel)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidArchLifecycleAndroidViewModel")
