//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidArchLifecycleComputableLiveData")
#ifdef RESTRICT_AndroidArchLifecycleComputableLiveData
#define INCLUDE_ALL_AndroidArchLifecycleComputableLiveData 0
#else
#define INCLUDE_ALL_AndroidArchLifecycleComputableLiveData 1
#endif
#undef RESTRICT_AndroidArchLifecycleComputableLiveData

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AndroidArchLifecycleComputableLiveData_) && (INCLUDE_ALL_AndroidArchLifecycleComputableLiveData || defined(INCLUDE_AndroidArchLifecycleComputableLiveData))
#define AndroidArchLifecycleComputableLiveData_

@class AndroidArchLifecycleLiveData;
@protocol JavaLangRunnable;

@interface AndroidArchLifecycleComputableLiveData : NSObject {
 @public
  id<JavaLangRunnable> mRefreshRunnable_;
  id<JavaLangRunnable> mInvalidationRunnable_;
}

#pragma mark Public

- (instancetype)init;

- (AndroidArchLifecycleLiveData * __nonnull)getLiveData;

- (void)invalidate;

#pragma mark Protected

- (id)compute;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidArchLifecycleComputableLiveData)

J2OBJC_FIELD_SETTER(AndroidArchLifecycleComputableLiveData, mRefreshRunnable_, id<JavaLangRunnable>)
J2OBJC_FIELD_SETTER(AndroidArchLifecycleComputableLiveData, mInvalidationRunnable_, id<JavaLangRunnable>)

FOUNDATION_EXPORT void AndroidArchLifecycleComputableLiveData_init(AndroidArchLifecycleComputableLiveData *self);

J2OBJC_TYPE_LITERAL_HEADER(AndroidArchLifecycleComputableLiveData)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidArchLifecycleComputableLiveData")
