//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidArchLifecycleMediatorLiveData")
#ifdef RESTRICT_AndroidArchLifecycleMediatorLiveData
#define INCLUDE_ALL_AndroidArchLifecycleMediatorLiveData 0
#else
#define INCLUDE_ALL_AndroidArchLifecycleMediatorLiveData 1
#endif
#undef RESTRICT_AndroidArchLifecycleMediatorLiveData

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AndroidArchLifecycleMediatorLiveData_) && (INCLUDE_ALL_AndroidArchLifecycleMediatorLiveData || defined(INCLUDE_AndroidArchLifecycleMediatorLiveData))
#define AndroidArchLifecycleMediatorLiveData_

#define RESTRICT_AndroidArchLifecycleMutableLiveData 1
#define INCLUDE_AndroidArchLifecycleMutableLiveData 1
#include "AndroidArchLifecycleMutableLiveData.h"

@class AndroidArchLifecycleLiveData;
@protocol AndroidArchLifecycleObserver;

@interface AndroidArchLifecycleMediatorLiveData : AndroidArchLifecycleMutableLiveData

#pragma mark Public

- (instancetype)init;

- (void)addSourceWithAndroidArchLifecycleLiveData:(AndroidArchLifecycleLiveData * __nonnull)source
                 withAndroidArchLifecycleObserver:(id<AndroidArchLifecycleObserver> __nonnull)onChanged;

- (void)removeSourceWithAndroidArchLifecycleLiveData:(AndroidArchLifecycleLiveData * __nonnull)toRemote;

#pragma mark Protected

- (void)onActive;

- (void)onInactive;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidArchLifecycleMediatorLiveData)

FOUNDATION_EXPORT void AndroidArchLifecycleMediatorLiveData_init(AndroidArchLifecycleMediatorLiveData *self);

FOUNDATION_EXPORT AndroidArchLifecycleMediatorLiveData *new_AndroidArchLifecycleMediatorLiveData_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AndroidArchLifecycleMediatorLiveData *create_AndroidArchLifecycleMediatorLiveData_init();

J2OBJC_TYPE_LITERAL_HEADER(AndroidArchLifecycleMediatorLiveData)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidArchLifecycleMediatorLiveData")
