//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidDatabaseCursorWindowAllocationException")
#ifdef RESTRICT_AndroidDatabaseCursorWindowAllocationException
#define INCLUDE_ALL_AndroidDatabaseCursorWindowAllocationException 0
#else
#define INCLUDE_ALL_AndroidDatabaseCursorWindowAllocationException 1
#endif
#undef RESTRICT_AndroidDatabaseCursorWindowAllocationException

#if !defined (AndroidDatabaseCursorWindowAllocationException_) && (INCLUDE_ALL_AndroidDatabaseCursorWindowAllocationException || defined(INCLUDE_AndroidDatabaseCursorWindowAllocationException))
#define AndroidDatabaseCursorWindowAllocationException_

#define RESTRICT_JavaLangRuntimeException 1
#define INCLUDE_JavaLangRuntimeException 1
#include "java/lang/RuntimeException.h"

@class JavaLangThrowable;

@interface AndroidDatabaseCursorWindowAllocationException : JavaLangRuntimeException

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)description_;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

- (instancetype)initWithJavaLangThrowable:(JavaLangThrowable *)arg0 NS_UNAVAILABLE;

- (instancetype)initWithNSString:(NSString *)arg0
           withJavaLangThrowable:(JavaLangThrowable *)arg1 NS_UNAVAILABLE;

- (instancetype)initWithNSString:(NSString *)arg0
           withJavaLangThrowable:(JavaLangThrowable *)arg1
                     withBoolean:(jboolean)arg2
                     withBoolean:(jboolean)arg3 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidDatabaseCursorWindowAllocationException)

FOUNDATION_EXPORT void AndroidDatabaseCursorWindowAllocationException_initWithNSString_(AndroidDatabaseCursorWindowAllocationException *self, NSString *description_);

FOUNDATION_EXPORT AndroidDatabaseCursorWindowAllocationException *new_AndroidDatabaseCursorWindowAllocationException_initWithNSString_(NSString *description_) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AndroidDatabaseCursorWindowAllocationException *create_AndroidDatabaseCursorWindowAllocationException_initWithNSString_(NSString *description_);

J2OBJC_TYPE_LITERAL_HEADER(AndroidDatabaseCursorWindowAllocationException)

#endif

#pragma pop_macro("INCLUDE_ALL_AndroidDatabaseCursorWindowAllocationException")
