//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidArchPersistenceRoomDao")
#ifdef RESTRICT_AndroidArchPersistenceRoomDao
#define INCLUDE_ALL_AndroidArchPersistenceRoomDao 0
#else
#define INCLUDE_ALL_AndroidArchPersistenceRoomDao 1
#endif
#undef RESTRICT_AndroidArchPersistenceRoomDao

#if !defined (AndroidArchPersistenceRoomDao_) && (INCLUDE_ALL_AndroidArchPersistenceRoomDao || defined(INCLUDE_AndroidArchPersistenceRoomDao))
#define AndroidArchPersistenceRoomDao_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@protocol AndroidArchPersistenceRoomDao < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidArchPersistenceRoomDao)

J2OBJC_TYPE_LITERAL_HEADER(AndroidArchPersistenceRoomDao)

#endif

#pragma pop_macro("INCLUDE_ALL_AndroidArchPersistenceRoomDao")
