//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_DNETDJustId")
#ifdef RESTRICT_DNETDJustId
#define INCLUDE_ALL_DNETDJustId 0
#else
#define INCLUDE_ALL_DNETDJustId 1
#endif
#undef RESTRICT_DNETDJustId

#if !defined (DNETDJustId_) && (INCLUDE_ALL_DNETDJustId || defined(INCLUDE_DNETDJustId))
#define DNETDJustId_

@class JavaLangLong;

@interface DNETDJustId : NSObject

#pragma mark Public

- (instancetype)init;

- (JavaLangLong *)getId;

- (void)setIdWithJavaLangLong:(JavaLangLong *)id_;

@end

J2OBJC_EMPTY_STATIC_INIT(DNETDJustId)

FOUNDATION_EXPORT void DNETDJustId_init(DNETDJustId *self);

FOUNDATION_EXPORT DNETDJustId *new_DNETDJustId_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT DNETDJustId *create_DNETDJustId_init();

J2OBJC_TYPE_LITERAL_HEADER(DNETDJustId)

@compatibility_alias CoTouchlabDroidconandroidSharedNetworkDaoJustId DNETDJustId;

#endif

#pragma pop_macro("INCLUDE_ALL_DNETDJustId")
