//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_DVMUserDetailViewModel")
#ifdef RESTRICT_DVMUserDetailViewModel
#define INCLUDE_ALL_DVMUserDetailViewModel 0
#else
#define INCLUDE_ALL_DVMUserDetailViewModel 1
#endif
#undef RESTRICT_DVMUserDetailViewModel

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (DVMUserDetailViewModel_) && (INCLUDE_ALL_DVMUserDetailViewModel || defined(INCLUDE_DVMUserDetailViewModel))
#define DVMUserDetailViewModel_

#define RESTRICT_AndroidArchLifecycleViewModel 1
#define INCLUDE_AndroidArchLifecycleViewModel 1
#include "AndroidArchLifecycleViewModel.h"

@class DVMUserDetailViewModel_Factory;
@protocol DVMUserDetailViewModel_Host;

@interface DVMUserDetailViewModel : AndroidArchLifecycleViewModel

#pragma mark Public

+ (DVMUserDetailViewModel_Factory *)factory;

+ (DVMUserDetailViewModel *)forIos;

- (void)unwire;

- (void)wireWithDVMUserDetailViewModel_Host:(id<DVMUserDetailViewModel_Host>)host
                                   withLong:(jlong)userId;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(DVMUserDetailViewModel)

FOUNDATION_EXPORT DVMUserDetailViewModel_Factory *DVMUserDetailViewModel_factory();

FOUNDATION_EXPORT DVMUserDetailViewModel *DVMUserDetailViewModel_forIos();

J2OBJC_TYPE_LITERAL_HEADER(DVMUserDetailViewModel)

@compatibility_alias CoTouchlabDroidconandroidSharedViewmodelUserDetailViewModel DVMUserDetailViewModel;

#endif

#if !defined (DVMUserDetailViewModel_Host_) && (INCLUDE_ALL_DVMUserDetailViewModel || defined(INCLUDE_DVMUserDetailViewModel_Host))
#define DVMUserDetailViewModel_Host_

@class DDATUserAccount;

@protocol DVMUserDetailViewModel_Host < JavaObject >

- (void)findUserError;

- (void)onUserFoundWithDDATUserAccount:(DDATUserAccount * __nonnull)userAccount;

@end

J2OBJC_EMPTY_STATIC_INIT(DVMUserDetailViewModel_Host)

J2OBJC_TYPE_LITERAL_HEADER(DVMUserDetailViewModel_Host)

#endif

#if !defined (DVMUserDetailViewModel_Factory_) && (INCLUDE_ALL_DVMUserDetailViewModel || defined(INCLUDE_DVMUserDetailViewModel_Factory))
#define DVMUserDetailViewModel_Factory_

#define RESTRICT_AndroidArchLifecycleViewModelProvider 1
#define INCLUDE_AndroidArchLifecycleViewModelProvider_NewInstanceFactory 1
#include "AndroidArchLifecycleViewModelProvider.h"

@class AndroidArchLifecycleViewModel;
@class DINTFindUserInteractor;
@class IOSClass;
@protocol IoReactivexFlowableTransformer;

@interface DVMUserDetailViewModel_Factory : AndroidArchLifecycleViewModelProvider_NewInstanceFactory {
 @public
  DINTFindUserInteractor *task_;
  id<IoReactivexFlowableTransformer> transformer_;
}

#pragma mark Public

- (AndroidArchLifecycleViewModel *)createWithIOSClass:(IOSClass *)modelClass;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(DVMUserDetailViewModel_Factory)

J2OBJC_FIELD_SETTER(DVMUserDetailViewModel_Factory, task_, DINTFindUserInteractor *)
J2OBJC_FIELD_SETTER(DVMUserDetailViewModel_Factory, transformer_, id<IoReactivexFlowableTransformer>)

FOUNDATION_EXPORT void DVMUserDetailViewModel_Factory_init(DVMUserDetailViewModel_Factory *self);

FOUNDATION_EXPORT DVMUserDetailViewModel_Factory *new_DVMUserDetailViewModel_Factory_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT DVMUserDetailViewModel_Factory *create_DVMUserDetailViewModel_Factory_init();

J2OBJC_TYPE_LITERAL_HEADER(DVMUserDetailViewModel_Factory)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_DVMUserDetailViewModel")
