//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Retrofit2ConverterGsonpackage_info")
#ifdef RESTRICT_Retrofit2ConverterGsonpackage_info
#define INCLUDE_ALL_Retrofit2ConverterGsonpackage_info 0
#else
#define INCLUDE_ALL_Retrofit2ConverterGsonpackage_info 1
#endif
#undef RESTRICT_Retrofit2ConverterGsonpackage_info

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_Retrofit2ConverterGsonpackage_info")
