platform :ios, '9.0'

install! 'cocoapods',
           :deterministic_uuids => false

target 'ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!



  # Pods for ios
    pod 'Firebase'
    pod 'Firebase/Messaging'
    pod 'Kingfisher', '~> 3.0'
    pod 'doppllib', :path => '../app/build'

  target 'iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
