//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Retrofit2Callback")
#ifdef RESTRICT_Retrofit2Callback
#define INCLUDE_ALL_Retrofit2Callback 0
#else
#define INCLUDE_ALL_Retrofit2Callback 1
#endif
#undef RESTRICT_Retrofit2Callback

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (Retrofit2Callback_) && (INCLUDE_ALL_Retrofit2Callback || defined(INCLUDE_Retrofit2Callback))
#define Retrofit2Callback_

@class JavaLangThrowable;
@class Retrofit2Response;
@protocol Retrofit2Call;

@protocol Retrofit2Callback < JavaObject >

- (void)onResponseWithRetrofit2Call:(id<Retrofit2Call> __nonnull)call
              withRetrofit2Response:(Retrofit2Response * __nonnull)response;

- (void)onFailureWithRetrofit2Call:(id<Retrofit2Call> __nonnull)call
             withJavaLangThrowable:(JavaLangThrowable * __nonnull)t;

@end

J2OBJC_EMPTY_STATIC_INIT(Retrofit2Callback)

J2OBJC_TYPE_LITERAL_HEADER(Retrofit2Callback)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_Retrofit2Callback")
