//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_IoReactivexSubscribersResourceSubscriber")
#ifdef RESTRICT_IoReactivexSubscribersResourceSubscriber
#define INCLUDE_ALL_IoReactivexSubscribersResourceSubscriber 0
#else
#define INCLUDE_ALL_IoReactivexSubscribersResourceSubscriber 1
#endif
#undef RESTRICT_IoReactivexSubscribersResourceSubscriber

#if !defined (IoReactivexSubscribersResourceSubscriber_) && (INCLUDE_ALL_IoReactivexSubscribersResourceSubscriber || defined(INCLUDE_IoReactivexSubscribersResourceSubscriber))
#define IoReactivexSubscribersResourceSubscriber_

#define RESTRICT_IoReactivexFlowableSubscriber 1
#define INCLUDE_IoReactivexFlowableSubscriber 1
#include "IoReactivexFlowableSubscriber.h"

#define RESTRICT_IoReactivexDisposablesDisposable 1
#define INCLUDE_IoReactivexDisposablesDisposable 1
#include "IoReactivexDisposablesDisposable.h"

@protocol OrgReactivestreamsSubscription;

@interface IoReactivexSubscribersResourceSubscriber : NSObject < IoReactivexFlowableSubscriber, IoReactivexDisposablesDisposable >

#pragma mark Public

- (instancetype)init;

- (void)addWithIoReactivexDisposablesDisposable:(id<IoReactivexDisposablesDisposable>)resource;

- (void)dispose;

- (jboolean)isDisposed;

- (void)onSubscribeWithOrgReactivestreamsSubscription:(id<OrgReactivestreamsSubscription>)s;

#pragma mark Protected

- (void)onStart;

- (void)requestWithLong:(jlong)n;

@end

J2OBJC_EMPTY_STATIC_INIT(IoReactivexSubscribersResourceSubscriber)

FOUNDATION_EXPORT void IoReactivexSubscribersResourceSubscriber_init(IoReactivexSubscribersResourceSubscriber *self);

J2OBJC_TYPE_LITERAL_HEADER(IoReactivexSubscribersResourceSubscriber)

#endif

#pragma pop_macro("INCLUDE_ALL_IoReactivexSubscribersResourceSubscriber")
