//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "IoReactivexDisposablesDisposable.h"
#include "IoReactivexExceptionsExceptions.h"
#include "IoReactivexFunctionsAction.h"
#include "IoReactivexInternalDisposablesDisposableHelper.h"
#include "IoReactivexInternalOperatorsSingleSingleDoAfterTerminate.h"
#include "IoReactivexPluginsRxJavaPlugins.h"
#include "IoReactivexSingle.h"
#include "IoReactivexSingleObserver.h"
#include "IoReactivexSingleSource.h"
#include "J2ObjC_source.h"
#include "java/lang/Throwable.h"

@interface IoReactivexInternalOperatorsSingleSingleDoAfterTerminate_DoAfterTerminateObserver ()

- (void)onAfterTerminate;

@end

__attribute__((unused)) static void IoReactivexInternalOperatorsSingleSingleDoAfterTerminate_DoAfterTerminateObserver_onAfterTerminate(IoReactivexInternalOperatorsSingleSingleDoAfterTerminate_DoAfterTerminateObserver *self);

@implementation IoReactivexInternalOperatorsSingleSingleDoAfterTerminate

- (instancetype)initWithIoReactivexSingleSource:(id<IoReactivexSingleSource>)source
                 withIoReactivexFunctionsAction:(id<IoReactivexFunctionsAction>)onAfterTerminate {
  IoReactivexInternalOperatorsSingleSingleDoAfterTerminate_initWithIoReactivexSingleSource_withIoReactivexFunctionsAction_(self, source, onAfterTerminate);
  return self;
}

- (void)subscribeActualWithIoReactivexSingleObserver:(id<IoReactivexSingleObserver>)s {
  [((id<IoReactivexSingleSource>) nil_chk(source_)) subscribeWithIoReactivexSingleObserver:create_IoReactivexInternalOperatorsSingleSingleDoAfterTerminate_DoAfterTerminateObserver_initWithIoReactivexSingleObserver_withIoReactivexFunctionsAction_(s, onAfterTerminate_)];
}

- (void)dealloc {
  RELEASE_(source_);
  RELEASE_(onAfterTerminate_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, 1, -1, -1 },
    { NULL, "V", 0x4, 2, 3, -1, 4, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithIoReactivexSingleSource:withIoReactivexFunctionsAction:);
  methods[1].selector = @selector(subscribeActualWithIoReactivexSingleObserver:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "source_", "LIoReactivexSingleSource;", .constantValue.asLong = 0, 0x10, -1, -1, 5, -1 },
    { "onAfterTerminate_", "LIoReactivexFunctionsAction;", .constantValue.asLong = 0, 0x10, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LIoReactivexSingleSource;LIoReactivexFunctionsAction;", "(Lio/reactivex/SingleSource<TT;>;Lio/reactivex/functions/Action;)V", "subscribeActual", "LIoReactivexSingleObserver;", "(Lio/reactivex/SingleObserver<-TT;>;)V", "Lio/reactivex/SingleSource<TT;>;", "LIoReactivexInternalOperatorsSingleSingleDoAfterTerminate_DoAfterTerminateObserver;", "<T:Ljava/lang/Object;>Lio/reactivex/Single<TT;>;" };
  static const J2ObjcClassInfo _IoReactivexInternalOperatorsSingleSingleDoAfterTerminate = { "SingleDoAfterTerminate", "io.reactivex.internal.operators.single", ptrTable, methods, fields, 7, 0x11, 2, 2, -1, 6, -1, 7, -1 };
  return &_IoReactivexInternalOperatorsSingleSingleDoAfterTerminate;
}

@end

void IoReactivexInternalOperatorsSingleSingleDoAfterTerminate_initWithIoReactivexSingleSource_withIoReactivexFunctionsAction_(IoReactivexInternalOperatorsSingleSingleDoAfterTerminate *self, id<IoReactivexSingleSource> source, id<IoReactivexFunctionsAction> onAfterTerminate) {
  IoReactivexSingle_init(self);
  JreStrongAssign(&self->source_, source);
  JreStrongAssign(&self->onAfterTerminate_, onAfterTerminate);
}

IoReactivexInternalOperatorsSingleSingleDoAfterTerminate *new_IoReactivexInternalOperatorsSingleSingleDoAfterTerminate_initWithIoReactivexSingleSource_withIoReactivexFunctionsAction_(id<IoReactivexSingleSource> source, id<IoReactivexFunctionsAction> onAfterTerminate) {
  J2OBJC_NEW_IMPL(IoReactivexInternalOperatorsSingleSingleDoAfterTerminate, initWithIoReactivexSingleSource_withIoReactivexFunctionsAction_, source, onAfterTerminate)
}

IoReactivexInternalOperatorsSingleSingleDoAfterTerminate *create_IoReactivexInternalOperatorsSingleSingleDoAfterTerminate_initWithIoReactivexSingleSource_withIoReactivexFunctionsAction_(id<IoReactivexSingleSource> source, id<IoReactivexFunctionsAction> onAfterTerminate) {
  J2OBJC_CREATE_IMPL(IoReactivexInternalOperatorsSingleSingleDoAfterTerminate, initWithIoReactivexSingleSource_withIoReactivexFunctionsAction_, source, onAfterTerminate)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(IoReactivexInternalOperatorsSingleSingleDoAfterTerminate)

@implementation IoReactivexInternalOperatorsSingleSingleDoAfterTerminate_DoAfterTerminateObserver

- (instancetype)initWithIoReactivexSingleObserver:(id<IoReactivexSingleObserver>)actual
                   withIoReactivexFunctionsAction:(id<IoReactivexFunctionsAction>)onAfterTerminate {
  IoReactivexInternalOperatorsSingleSingleDoAfterTerminate_DoAfterTerminateObserver_initWithIoReactivexSingleObserver_withIoReactivexFunctionsAction_(self, actual, onAfterTerminate);
  return self;
}

- (void)onSubscribeWithIoReactivexDisposablesDisposable:(id<IoReactivexDisposablesDisposable>)d {
  if (IoReactivexInternalDisposablesDisposableHelper_validateWithIoReactivexDisposablesDisposable_withIoReactivexDisposablesDisposable_(self->d_, d)) {
    JreStrongAssign(&self->d_, d);
    [((id<IoReactivexSingleObserver>) nil_chk(actual_)) onSubscribeWithIoReactivexDisposablesDisposable:self];
  }
}

- (void)onSuccessWithId:(id)t {
  [((id<IoReactivexSingleObserver>) nil_chk(actual_)) onSuccessWithId:t];
  IoReactivexInternalOperatorsSingleSingleDoAfterTerminate_DoAfterTerminateObserver_onAfterTerminate(self);
}

- (void)onErrorWithJavaLangThrowable:(JavaLangThrowable *)e {
  [((id<IoReactivexSingleObserver>) nil_chk(actual_)) onErrorWithJavaLangThrowable:e];
  IoReactivexInternalOperatorsSingleSingleDoAfterTerminate_DoAfterTerminateObserver_onAfterTerminate(self);
}

- (void)dispose {
  [((id<IoReactivexDisposablesDisposable>) nil_chk(d_)) dispose];
}

- (jboolean)isDisposed {
  return [((id<IoReactivexDisposablesDisposable>) nil_chk(d_)) isDisposed];
}

- (void)onAfterTerminate {
  IoReactivexInternalOperatorsSingleSingleDoAfterTerminate_DoAfterTerminateObserver_onAfterTerminate(self);
}

- (void)dealloc {
  RELEASE_(actual_);
  RELEASE_(onAfterTerminate_);
  RELEASE_(d_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, 0, -1, 1, -1, -1 },
    { NULL, "V", 0x1, 2, 3, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 4, 5, -1, 6, -1, -1 },
    { NULL, "V", 0x1, 7, 8, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x2, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithIoReactivexSingleObserver:withIoReactivexFunctionsAction:);
  methods[1].selector = @selector(onSubscribeWithIoReactivexDisposablesDisposable:);
  methods[2].selector = @selector(onSuccessWithId:);
  methods[3].selector = @selector(onErrorWithJavaLangThrowable:);
  methods[4].selector = @selector(dispose);
  methods[5].selector = @selector(isDisposed);
  methods[6].selector = @selector(onAfterTerminate);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "actual_", "LIoReactivexSingleObserver;", .constantValue.asLong = 0, 0x10, -1, -1, 9, -1 },
    { "onAfterTerminate_", "LIoReactivexFunctionsAction;", .constantValue.asLong = 0, 0x10, -1, -1, -1, -1 },
    { "d_", "LIoReactivexDisposablesDisposable;", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LIoReactivexSingleObserver;LIoReactivexFunctionsAction;", "(Lio/reactivex/SingleObserver<-TT;>;Lio/reactivex/functions/Action;)V", "onSubscribe", "LIoReactivexDisposablesDisposable;", "onSuccess", "LNSObject;", "(TT;)V", "onError", "LJavaLangThrowable;", "Lio/reactivex/SingleObserver<-TT;>;", "LIoReactivexInternalOperatorsSingleSingleDoAfterTerminate;", "<T:Ljava/lang/Object;>Ljava/lang/Object;Lio/reactivex/SingleObserver<TT;>;Lio/reactivex/disposables/Disposable;" };
  static const J2ObjcClassInfo _IoReactivexInternalOperatorsSingleSingleDoAfterTerminate_DoAfterTerminateObserver = { "DoAfterTerminateObserver", "io.reactivex.internal.operators.single", ptrTable, methods, fields, 7, 0x18, 7, 3, 10, -1, -1, 11, -1 };
  return &_IoReactivexInternalOperatorsSingleSingleDoAfterTerminate_DoAfterTerminateObserver;
}

@end

void IoReactivexInternalOperatorsSingleSingleDoAfterTerminate_DoAfterTerminateObserver_initWithIoReactivexSingleObserver_withIoReactivexFunctionsAction_(IoReactivexInternalOperatorsSingleSingleDoAfterTerminate_DoAfterTerminateObserver *self, id<IoReactivexSingleObserver> actual, id<IoReactivexFunctionsAction> onAfterTerminate) {
  NSObject_init(self);
  JreStrongAssign(&self->actual_, actual);
  JreStrongAssign(&self->onAfterTerminate_, onAfterTerminate);
}

IoReactivexInternalOperatorsSingleSingleDoAfterTerminate_DoAfterTerminateObserver *new_IoReactivexInternalOperatorsSingleSingleDoAfterTerminate_DoAfterTerminateObserver_initWithIoReactivexSingleObserver_withIoReactivexFunctionsAction_(id<IoReactivexSingleObserver> actual, id<IoReactivexFunctionsAction> onAfterTerminate) {
  J2OBJC_NEW_IMPL(IoReactivexInternalOperatorsSingleSingleDoAfterTerminate_DoAfterTerminateObserver, initWithIoReactivexSingleObserver_withIoReactivexFunctionsAction_, actual, onAfterTerminate)
}

IoReactivexInternalOperatorsSingleSingleDoAfterTerminate_DoAfterTerminateObserver *create_IoReactivexInternalOperatorsSingleSingleDoAfterTerminate_DoAfterTerminateObserver_initWithIoReactivexSingleObserver_withIoReactivexFunctionsAction_(id<IoReactivexSingleObserver> actual, id<IoReactivexFunctionsAction> onAfterTerminate) {
  J2OBJC_CREATE_IMPL(IoReactivexInternalOperatorsSingleSingleDoAfterTerminate_DoAfterTerminateObserver, initWithIoReactivexSingleObserver_withIoReactivexFunctionsAction_, actual, onAfterTerminate)
}

void IoReactivexInternalOperatorsSingleSingleDoAfterTerminate_DoAfterTerminateObserver_onAfterTerminate(IoReactivexInternalOperatorsSingleSingleDoAfterTerminate_DoAfterTerminateObserver *self) {
  @try {
    [((id<IoReactivexFunctionsAction>) nil_chk(self->onAfterTerminate_)) run];
  }
  @catch (JavaLangThrowable *ex) {
    IoReactivexExceptionsExceptions_throwIfFatalWithJavaLangThrowable_(ex);
    IoReactivexPluginsRxJavaPlugins_onErrorWithJavaLangThrowable_(ex);
  }
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(IoReactivexInternalOperatorsSingleSingleDoAfterTerminate_DoAfterTerminateObserver)
