//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "IoReactivexDisposablesDisposable.h"
#include "IoReactivexFunctionsConsumer.h"
#include "IoReactivexInternalFunctionsFunctions.h"
#include "IoReactivexInternalOperatorsObservableObservableAutoConnect.h"
#include "IoReactivexInternalOperatorsObservableObservableRefCount.h"
#include "IoReactivexInternalUtilConnectConsumer.h"
#include "IoReactivexObservable.h"
#include "IoReactivexObservablesConnectableObservable.h"
#include "IoReactivexPluginsRxJavaPlugins.h"
#include "J2ObjC_source.h"

@implementation IoReactivexObservablesConnectableObservable

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  IoReactivexObservablesConnectableObservable_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (void)connectWithIoReactivexFunctionsConsumer:(id<IoReactivexFunctionsConsumer> __nonnull)connection {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
}

- (id<IoReactivexDisposablesDisposable>)connect {
  IoReactivexInternalUtilConnectConsumer *cc = create_IoReactivexInternalUtilConnectConsumer_init();
  [self connectWithIoReactivexFunctionsConsumer:cc];
  return cc->disposable_;
}

- (IoReactivexObservable * __nonnull)refCount {
  return IoReactivexPluginsRxJavaPlugins_onAssemblyWithIoReactivexObservable_(create_IoReactivexInternalOperatorsObservableObservableRefCount_initWithIoReactivexObservablesConnectableObservable_(self));
}

- (IoReactivexObservable * __nonnull)autoConnect {
  return [self autoConnectWithInt:1];
}

- (IoReactivexObservable * __nonnull)autoConnectWithInt:(jint)numberOfSubscribers {
  return [self autoConnectWithInt:numberOfSubscribers withIoReactivexFunctionsConsumer:IoReactivexInternalFunctionsFunctions_emptyConsumer()];
}

- (IoReactivexObservable * __nonnull)autoConnectWithInt:(jint)numberOfSubscribers
                       withIoReactivexFunctionsConsumer:(id<IoReactivexFunctionsConsumer> __nonnull)connection {
  if (numberOfSubscribers <= 0) {
    [self connectWithIoReactivexFunctionsConsumer:connection];
    return IoReactivexPluginsRxJavaPlugins_onAssemblyWithIoReactivexObservablesConnectableObservable_(self);
  }
  return IoReactivexPluginsRxJavaPlugins_onAssemblyWithIoReactivexObservable_(create_IoReactivexInternalOperatorsObservableObservableAutoConnect_initWithIoReactivexObservablesConnectableObservable_withInt_withIoReactivexFunctionsConsumer_(self, numberOfSubscribers, connection));
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 0, 1, -1, 2, -1, -1 },
    { NULL, "LIoReactivexDisposablesDisposable;", 0x11, -1, -1, -1, -1, -1, -1 },
    { NULL, "LIoReactivexObservable;", 0x1, -1, -1, -1, 3, -1, -1 },
    { NULL, "LIoReactivexObservable;", 0x1, -1, -1, -1, 3, -1, -1 },
    { NULL, "LIoReactivexObservable;", 0x1, 4, 5, -1, 6, -1, -1 },
    { NULL, "LIoReactivexObservable;", 0x1, 4, 7, -1, 8, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(connectWithIoReactivexFunctionsConsumer:);
  methods[2].selector = @selector(connect);
  methods[3].selector = @selector(refCount);
  methods[4].selector = @selector(autoConnect);
  methods[5].selector = @selector(autoConnectWithInt:);
  methods[6].selector = @selector(autoConnectWithInt:withIoReactivexFunctionsConsumer:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "connect", "LIoReactivexFunctionsConsumer;", "(Lio/reactivex/functions/Consumer<-Lio/reactivex/disposables/Disposable;>;)V", "()Lio/reactivex/Observable<TT;>;", "autoConnect", "I", "(I)Lio/reactivex/Observable<TT;>;", "ILIoReactivexFunctionsConsumer;", "(ILio/reactivex/functions/Consumer<-Lio/reactivex/disposables/Disposable;>;)Lio/reactivex/Observable<TT;>;", "<T:Ljava/lang/Object;>Lio/reactivex/Observable<TT;>;" };
  static const J2ObjcClassInfo _IoReactivexObservablesConnectableObservable = { "ConnectableObservable", "io.reactivex.observables", ptrTable, methods, NULL, 7, 0x401, 7, 0, -1, -1, -1, 9, -1 };
  return &_IoReactivexObservablesConnectableObservable;
}

@end

void IoReactivexObservablesConnectableObservable_init(IoReactivexObservablesConnectableObservable *self) {
  IoReactivexObservable_init(self);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(IoReactivexObservablesConnectableObservable)
