//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_IoReactivexMaybeOperator")
#ifdef RESTRICT_IoReactivexMaybeOperator
#define INCLUDE_ALL_IoReactivexMaybeOperator 0
#else
#define INCLUDE_ALL_IoReactivexMaybeOperator 1
#endif
#undef RESTRICT_IoReactivexMaybeOperator

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (IoReactivexMaybeOperator_) && (INCLUDE_ALL_IoReactivexMaybeOperator || defined(INCLUDE_IoReactivexMaybeOperator))
#define IoReactivexMaybeOperator_

@protocol IoReactivexMaybeObserver;

@protocol IoReactivexMaybeOperator < JavaObject >

- (id<IoReactivexMaybeObserver> __nonnull)applyWithIoReactivexMaybeObserver:(id<IoReactivexMaybeObserver> __nonnull)observer;

@end

J2OBJC_EMPTY_STATIC_INIT(IoReactivexMaybeOperator)

J2OBJC_TYPE_LITERAL_HEADER(IoReactivexMaybeOperator)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_IoReactivexMaybeOperator")
