//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidArchCoreInternalSafeIterableMap")
#ifdef RESTRICT_AndroidArchCoreInternalSafeIterableMap
#define INCLUDE_ALL_AndroidArchCoreInternalSafeIterableMap 0
#else
#define INCLUDE_ALL_AndroidArchCoreInternalSafeIterableMap 1
#endif
#undef RESTRICT_AndroidArchCoreInternalSafeIterableMap
#ifdef INCLUDE_AndroidArchCoreInternalSafeIterableMap_IteratorWithAdditions
#define INCLUDE_AndroidArchCoreInternalSafeIterableMap_SupportRemove 1
#endif
#ifdef INCLUDE_AndroidArchCoreInternalSafeIterableMap_AscendingIterator
#define INCLUDE_AndroidArchCoreInternalSafeIterableMap_ListIterator 1
#endif
#ifdef INCLUDE_AndroidArchCoreInternalSafeIterableMap_ListIterator
#define INCLUDE_AndroidArchCoreInternalSafeIterableMap_SupportRemove 1
#endif

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AndroidArchCoreInternalSafeIterableMap_) && (INCLUDE_ALL_AndroidArchCoreInternalSafeIterableMap || defined(INCLUDE_AndroidArchCoreInternalSafeIterableMap))
#define AndroidArchCoreInternalSafeIterableMap_

#define RESTRICT_JavaLangIterable 1
#define INCLUDE_JavaLangIterable 1
#include "java/lang/Iterable.h"

@class AndroidArchCoreInternalSafeIterableMap_Entry;
@class AndroidArchCoreInternalSafeIterableMap_IteratorWithAdditions;
@protocol JavaUtilFunctionConsumer;
@protocol JavaUtilIterator;
@protocol JavaUtilMap_Entry;
@protocol JavaUtilSpliterator;

@interface AndroidArchCoreInternalSafeIterableMap : NSObject < JavaLangIterable >

#pragma mark Public

- (instancetype)init;

- (id<JavaUtilIterator>)descendingIterator;

- (id<JavaUtilMap_Entry>)eldest;

- (jboolean)isEqual:(id)obj;

- (id<JavaUtilIterator> __nonnull)iterator;

- (AndroidArchCoreInternalSafeIterableMap_IteratorWithAdditions *)iteratorWithAdditions;

- (id<JavaUtilMap_Entry>)newest OBJC_METHOD_FAMILY_NONE;

- (id)putIfAbsentWithId:(id __nonnull)key
                 withId:(id __nonnull)v;

- (id)removeWithId:(id __nonnull)key;

- (jint)size;

- (NSString *)description;

#pragma mark Protected

- (AndroidArchCoreInternalSafeIterableMap_Entry *)getWithId:(id)k;

- (AndroidArchCoreInternalSafeIterableMap_Entry *)putWithId:(id __nonnull)key
                                                     withId:(id __nonnull)v;

#pragma mark Package-Private

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidArchCoreInternalSafeIterableMap)

FOUNDATION_EXPORT void AndroidArchCoreInternalSafeIterableMap_init(AndroidArchCoreInternalSafeIterableMap *self);

FOUNDATION_EXPORT AndroidArchCoreInternalSafeIterableMap *new_AndroidArchCoreInternalSafeIterableMap_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AndroidArchCoreInternalSafeIterableMap *create_AndroidArchCoreInternalSafeIterableMap_init();

J2OBJC_TYPE_LITERAL_HEADER(AndroidArchCoreInternalSafeIterableMap)

#endif

#if !defined (AndroidArchCoreInternalSafeIterableMap_SupportRemove_) && (INCLUDE_ALL_AndroidArchCoreInternalSafeIterableMap || defined(INCLUDE_AndroidArchCoreInternalSafeIterableMap_SupportRemove))
#define AndroidArchCoreInternalSafeIterableMap_SupportRemove_

@class AndroidArchCoreInternalSafeIterableMap_Entry;

@protocol AndroidArchCoreInternalSafeIterableMap_SupportRemove < JavaObject >

- (void)supportRemoveWithAndroidArchCoreInternalSafeIterableMap_Entry:(AndroidArchCoreInternalSafeIterableMap_Entry * __nonnull)entry_;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidArchCoreInternalSafeIterableMap_SupportRemove)

J2OBJC_TYPE_LITERAL_HEADER(AndroidArchCoreInternalSafeIterableMap_SupportRemove)

#endif

#if !defined (AndroidArchCoreInternalSafeIterableMap_ListIterator_) && (INCLUDE_ALL_AndroidArchCoreInternalSafeIterableMap || defined(INCLUDE_AndroidArchCoreInternalSafeIterableMap_ListIterator))
#define AndroidArchCoreInternalSafeIterableMap_ListIterator_

#define RESTRICT_JavaUtilIterator 1
#define INCLUDE_JavaUtilIterator 1
#include "java/util/Iterator.h"

@class AndroidArchCoreInternalSafeIterableMap_Entry;
@protocol JavaUtilFunctionConsumer;
@protocol JavaUtilMap_Entry;

@interface AndroidArchCoreInternalSafeIterableMap_ListIterator : NSObject < JavaUtilIterator, AndroidArchCoreInternalSafeIterableMap_SupportRemove > {
 @public
  AndroidArchCoreInternalSafeIterableMap_Entry *mExpectedEnd_;
  AndroidArchCoreInternalSafeIterableMap_Entry *mNext_;
}

#pragma mark Public

- (jboolean)hasNext;

- (id<JavaUtilMap_Entry>)next;

- (void)supportRemoveWithAndroidArchCoreInternalSafeIterableMap_Entry:(AndroidArchCoreInternalSafeIterableMap_Entry * __nonnull)entry_;

#pragma mark Package-Private

- (instancetype)initWithAndroidArchCoreInternalSafeIterableMap_Entry:(AndroidArchCoreInternalSafeIterableMap_Entry *)start
                    withAndroidArchCoreInternalSafeIterableMap_Entry:(AndroidArchCoreInternalSafeIterableMap_Entry *)expectedEnd;

- (AndroidArchCoreInternalSafeIterableMap_Entry *)backwardWithAndroidArchCoreInternalSafeIterableMap_Entry:(AndroidArchCoreInternalSafeIterableMap_Entry *)entry_;

- (AndroidArchCoreInternalSafeIterableMap_Entry *)forwardWithAndroidArchCoreInternalSafeIterableMap_Entry:(AndroidArchCoreInternalSafeIterableMap_Entry *)entry_;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidArchCoreInternalSafeIterableMap_ListIterator)

J2OBJC_FIELD_SETTER(AndroidArchCoreInternalSafeIterableMap_ListIterator, mExpectedEnd_, AndroidArchCoreInternalSafeIterableMap_Entry *)
J2OBJC_FIELD_SETTER(AndroidArchCoreInternalSafeIterableMap_ListIterator, mNext_, AndroidArchCoreInternalSafeIterableMap_Entry *)

FOUNDATION_EXPORT void AndroidArchCoreInternalSafeIterableMap_ListIterator_initWithAndroidArchCoreInternalSafeIterableMap_Entry_withAndroidArchCoreInternalSafeIterableMap_Entry_(AndroidArchCoreInternalSafeIterableMap_ListIterator *self, AndroidArchCoreInternalSafeIterableMap_Entry *start, AndroidArchCoreInternalSafeIterableMap_Entry *expectedEnd);

J2OBJC_TYPE_LITERAL_HEADER(AndroidArchCoreInternalSafeIterableMap_ListIterator)

#endif

#if !defined (AndroidArchCoreInternalSafeIterableMap_AscendingIterator_) && (INCLUDE_ALL_AndroidArchCoreInternalSafeIterableMap || defined(INCLUDE_AndroidArchCoreInternalSafeIterableMap_AscendingIterator))
#define AndroidArchCoreInternalSafeIterableMap_AscendingIterator_

@class AndroidArchCoreInternalSafeIterableMap_Entry;

@interface AndroidArchCoreInternalSafeIterableMap_AscendingIterator : AndroidArchCoreInternalSafeIterableMap_ListIterator

#pragma mark Package-Private

- (instancetype)initWithAndroidArchCoreInternalSafeIterableMap_Entry:(AndroidArchCoreInternalSafeIterableMap_Entry *)start
                    withAndroidArchCoreInternalSafeIterableMap_Entry:(AndroidArchCoreInternalSafeIterableMap_Entry *)expectedEnd;

- (AndroidArchCoreInternalSafeIterableMap_Entry *)backwardWithAndroidArchCoreInternalSafeIterableMap_Entry:(AndroidArchCoreInternalSafeIterableMap_Entry *)entry_;

- (AndroidArchCoreInternalSafeIterableMap_Entry *)forwardWithAndroidArchCoreInternalSafeIterableMap_Entry:(AndroidArchCoreInternalSafeIterableMap_Entry *)entry_;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidArchCoreInternalSafeIterableMap_AscendingIterator)

FOUNDATION_EXPORT void AndroidArchCoreInternalSafeIterableMap_AscendingIterator_initWithAndroidArchCoreInternalSafeIterableMap_Entry_withAndroidArchCoreInternalSafeIterableMap_Entry_(AndroidArchCoreInternalSafeIterableMap_AscendingIterator *self, AndroidArchCoreInternalSafeIterableMap_Entry *start, AndroidArchCoreInternalSafeIterableMap_Entry *expectedEnd);

FOUNDATION_EXPORT AndroidArchCoreInternalSafeIterableMap_AscendingIterator *new_AndroidArchCoreInternalSafeIterableMap_AscendingIterator_initWithAndroidArchCoreInternalSafeIterableMap_Entry_withAndroidArchCoreInternalSafeIterableMap_Entry_(AndroidArchCoreInternalSafeIterableMap_Entry *start, AndroidArchCoreInternalSafeIterableMap_Entry *expectedEnd) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AndroidArchCoreInternalSafeIterableMap_AscendingIterator *create_AndroidArchCoreInternalSafeIterableMap_AscendingIterator_initWithAndroidArchCoreInternalSafeIterableMap_Entry_withAndroidArchCoreInternalSafeIterableMap_Entry_(AndroidArchCoreInternalSafeIterableMap_Entry *start, AndroidArchCoreInternalSafeIterableMap_Entry *expectedEnd);

J2OBJC_TYPE_LITERAL_HEADER(AndroidArchCoreInternalSafeIterableMap_AscendingIterator)

#endif

#if !defined (AndroidArchCoreInternalSafeIterableMap_IteratorWithAdditions_) && (INCLUDE_ALL_AndroidArchCoreInternalSafeIterableMap || defined(INCLUDE_AndroidArchCoreInternalSafeIterableMap_IteratorWithAdditions))
#define AndroidArchCoreInternalSafeIterableMap_IteratorWithAdditions_

#define RESTRICT_JavaUtilIterator 1
#define INCLUDE_JavaUtilIterator 1
#include "java/util/Iterator.h"

@class AndroidArchCoreInternalSafeIterableMap_Entry;
@protocol JavaUtilFunctionConsumer;
@protocol JavaUtilMap_Entry;

@interface AndroidArchCoreInternalSafeIterableMap_IteratorWithAdditions : NSObject < JavaUtilIterator, AndroidArchCoreInternalSafeIterableMap_SupportRemove >

#pragma mark Public

- (jboolean)hasNext;

- (id<JavaUtilMap_Entry>)next;

- (void)supportRemoveWithAndroidArchCoreInternalSafeIterableMap_Entry:(AndroidArchCoreInternalSafeIterableMap_Entry * __nonnull)entry_;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidArchCoreInternalSafeIterableMap_IteratorWithAdditions)

J2OBJC_TYPE_LITERAL_HEADER(AndroidArchCoreInternalSafeIterableMap_IteratorWithAdditions)

#endif

#if !defined (AndroidArchCoreInternalSafeIterableMap_Entry_) && (INCLUDE_ALL_AndroidArchCoreInternalSafeIterableMap || defined(INCLUDE_AndroidArchCoreInternalSafeIterableMap_Entry))
#define AndroidArchCoreInternalSafeIterableMap_Entry_

#define RESTRICT_JavaUtilMap 1
#define INCLUDE_JavaUtilMap_Entry 1
#include "java/util/Map.h"

@interface AndroidArchCoreInternalSafeIterableMap_Entry : NSObject < JavaUtilMap_Entry > {
 @public
  id mKey_;
  id mValue_;
  AndroidArchCoreInternalSafeIterableMap_Entry *mNext_;
  AndroidArchCoreInternalSafeIterableMap_Entry *mPrevious_;
}

#pragma mark Public

- (jboolean)isEqual:(id)obj;

- (id __nonnull)getKey;

- (id __nonnull)getValue;

- (id)setValueWithId:(id)value;

- (NSString *)description;

#pragma mark Package-Private

- (instancetype)initWithId:(id __nonnull)key
                    withId:(id __nonnull)value;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidArchCoreInternalSafeIterableMap_Entry)

J2OBJC_FIELD_SETTER(AndroidArchCoreInternalSafeIterableMap_Entry, mKey_, id)
J2OBJC_FIELD_SETTER(AndroidArchCoreInternalSafeIterableMap_Entry, mValue_, id)
J2OBJC_FIELD_SETTER(AndroidArchCoreInternalSafeIterableMap_Entry, mNext_, AndroidArchCoreInternalSafeIterableMap_Entry *)
J2OBJC_FIELD_SETTER(AndroidArchCoreInternalSafeIterableMap_Entry, mPrevious_, AndroidArchCoreInternalSafeIterableMap_Entry *)

FOUNDATION_EXPORT void AndroidArchCoreInternalSafeIterableMap_Entry_initWithId_withId_(AndroidArchCoreInternalSafeIterableMap_Entry *self, id key, id value);

FOUNDATION_EXPORT AndroidArchCoreInternalSafeIterableMap_Entry *new_AndroidArchCoreInternalSafeIterableMap_Entry_initWithId_withId_(id key, id value) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AndroidArchCoreInternalSafeIterableMap_Entry *create_AndroidArchCoreInternalSafeIterableMap_Entry_initWithId_withId_(id key, id value);

J2OBJC_TYPE_LITERAL_HEADER(AndroidArchCoreInternalSafeIterableMap_Entry)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidArchCoreInternalSafeIterableMap")
